num1=int(input("enter the 1st number:"))
num2=int(input("enter the 2st number:"))
print("addition:",num1+num2)
print("subtraction:",num1-num2)
print("multiplication:",num1*num2)
print("division:",num1/num2)
print("modulus:",num1%num2)
print("floor division:",num1//num2)
print("power:",num1**num2)